name: Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Enable RDP
      run: |
        net user admin P@ss2022
        net localgroup administrators runneradmin /add
